# ~/.config/wheel/advanced.wheel.yaml
models:
  - "gpt-4"
  - "gpt-3.5-turbo"
  - "gpt-4"  # Duplicate to test deduplication

completion:
  settings:
    temperature: 0.7
    topP: 1.0
    frequencyPenalty: 0.0
    presencePenalty: 0.0
  defaults:
    model: "gpt-4"
    maxLength: 1000

tools:
  enabled:
    - "calculator"
    - "web_search"
  calculator:
    precision: 4
    format: "decimal"
  web_search:
    engine: "brave"
    maxResults: 5
