models:
  openai:
    provider: "openai"
    name: "gpt-4o-mini"
  claude:
    provider: "anthropic"
    name: "claude-3-5-haiku-latest"
activeModel: "claude"
theme:
  light:
    background: "#ffffff"
    text: "#000000"
  dark:
    background: "#000000"
    text: "#ffffff"
dbPath: ".slop/slop.db"
