# yaml-language-server: $schema=https://raw.githubusercontent.com/isaacphi/slop/refs/heads/main/internal/config/schema.json

presets:
  gemini:
    provider: googleai
    name: gemini-1.5-flash
    maxTokens: 1000
  openai:
    provider: openai
    name: gpt-4o
  claude:
    provider: anthropic
    name: claude-3-5-haiku-latest
activeModel: claude
log:
  logFile: ""
  logLevel: INFO
dbPath: .slop/slop.db
internal:
  model: "openai"
  summaryPrompt: >
    Please provide a brief, concise summary of the following conversation.
    Focus on the main topics discussed and key points.
    The purpose is to quickly identify a conversation in a list.
    Summary should be less than 8 words long.
