models:
  openai:
    provider: "openai"
    name: "gpt-4o-mini"
  claude:
    provider: "anthropic"
    name: "claude-3-5-haiku-latest"
activeModel: "claude"
dbPath: ".slop/slop.db"
internal:
  model: "openai"
  summaryPrompt: >
    Please provide a brief, concise summary of the following conversation.
    Focus on the main topics discussed and key points.
    The purpose is to quickly identify a conversation in a list.
    Summary should be less than 8 words long.
