models:
  gemini:
    provider: googleai
    name: gemini-1.5-flash
    maxTokens: 1000
    tools:
      getCurrentWeather:
        description: Get the current weather in a given location
        parameters:
          type: object
          properties:
            location:
              type: string
              description: The city and state, e.g. San Francisco, CA
            unit:
              type: string
              enum: [fahrenheit, celsius]
          required: [location, unit]
      essay:
        description: wrie an essay
        parameters:
          type: object
          properties:
            content:
              type: string
              description: short essay content
            name:
              type: string
              description: essay name
  openai:
    provider: openai
    name: gpt-4o
    tools:
      getCurrentWeather:
        description: Get the current weather in a given location
        parameters:
          type: object
          properties:
            location:
              type: string
              description: The city and state, e.g. San Francisco, CA
            unit:
              type: string
              enum: [fahrenheit, celsius]
          required: [location, unit]
  claude:
    provider: anthropic
    name: claude-3-5-haiku-latest
    tools:
      getCurrentWeather:
        description: Get the current weather in a given location
        parameters:
          type: object
          properties:
            location:
              type: string
              description: The city and state, e.g. San Francisco, CA
            unit:
              type: string
              enum: [fahrenheit, celsius]
          required: [location, unit]
activeModel: claude
log:
  logFile: ""
  logLevel: INFO
dbPath: .slop/slop.db
agent:
  autoApproveFunctions: true
internal:
  model: "openai"
  summaryPrompt: >
    Please provide a brief, concise summary of the following conversation.
    Focus on the main topics discussed and key points.
    The purpose is to quickly identify a conversation in a list.
    Summary should be less than 8 words long.
