models:
  gpt4:
    provider: "openai"
    name: "gpt-4"
  gpt35:
    provider: "openai"
    name: "gpt-3.5-turbo"
theme:
  light:
    background: "#ffffff"
    text: "#000000"
  dark:
    background: "#000000"
    text: "#ffffff"
maxTokens: 8000
temperature: 0.7
