# ./.wheel/advanced.wheel.yaml
completion:
  settings:
    temperature: 0.9  # Override specific nested value
    streamOutput: true  # Add new nested value
  defaults:
    maxLength: 2000  # Override nested value

tools:
  enabled:
    - "calculator"  # Duplicate to test deduplication
    - "code_analysis"  # New value
  calculator:
    precision: 6  # Override nested value
  code_analysis:  # New nested object
    languages:
      - "python"
      - "javascript"
    maxFileSize: "10mb"
